//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyInformationalVersionAttribute("1.1.1-nolog4net")]
[assembly: AssemblyFileVersionAttribute("1.1.1-nolog4net")]

// Generated by the MSBuild WriteCodeFragment class.

