//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyInformationalVersionAttribute("2020.10.08-ID2649a2b")]
[assembly: AssemblyFileVersionAttribute("2020.10.08-ID2649a2b")]

// Generated by the MSBuild WriteCodeFragment class.

